# TODO: re-enable Metric/AbcSize, Metrics/CyclomaticComplexity, and Metrics/PerceivedComplexity
AllCops:
  DisplayCopNames: true
  NewCops: disable
  SuggestExtensions: false
# Disable ambiguous block due to breaking crontab.where example https://www.inspec.io/docs/reference/resources/crontab/
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "controls/**/*"
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "**/**/*_spec.rb"
Metrics/ClassLength:
  Max: 300
Layout/LineLength:
  Max: 280
Metrics/MethodLength:
  Max: 30
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/PredicatePrefix:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: compact
